services:
  - type: web
    name: growfund-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=growfund.minimal_settings
      python manage.py migrate --settings=growfund.minimal_settings
    startCommand: |
      python manage.py runserver 0.0.0.0:$PORT --settings=growfund.minimal_settings
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free