services:
  - type: web
    name: growfund-backend
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn growfund.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: growfund.settings
    plan: free